### ISSUE TITLE
simulation checklist

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/crokinole#5]
* [ ] making 20 logic
* [ ] exterior wall logic
* [ ] debug click to get location
* [ ] set scenario
* [ ] set size / refresh
